# Add reviewers to PR
addReviewers: true

# Set PR's author as an assignee
addAssignees: author

# A list of reviewers to be added to the PR
reviewers:
  - shorodilov
  - PonomaryovVladyslav

# A number of reviewers added to the PR
# 0 means add all listed reviewers
numberOfReviewers: 0
