version: "3.9"

services:
  db:
    image: postgres:15.1
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-init.d:ro

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_SERVERMODE=False
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - db
    links:
      - "db:postgresql-server"

volumes:
  db:
  pgadmin:
